apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-service-ingress
  namespace: file-service-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"   # IMPORTANT
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: file.cleanerp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: file-service
                port:
                  number: 4002
